100-hours-a-week/18-team-timeline-be

backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
backend/src/main/java/com/tamnara/backend/news/repository/NewsImageRepository.java
backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java

Reverts 100-hours-a-week/18-team-timeline-be#28

Revert "update: 핫이슈 뉴스 응답 구조 수정 및 이미지 필드 네이밍 통일, 중복 이미지 대응"

---

backend/src/main/java/com/tamnara/backend/global/config/SecurityConfig.java
backend/src/main/java/com/tamnara/backend/global/config/SwaggerConfig.java
backend/src/main/java/com/tamnara/backend/global/config/WebClientConfig.java
backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
backend/src/main/resources/application.properties

refactor: FE 및 BE URL, EC2 Public URL 환경변수화, 타임라인 카드 저장 로직 수정

---

.github/workflows/backend-check.yaml
.github/workflows/scripts/build.sh
backend/config/checkstyle/checkstyle.xml

add build.sh

---

.github/workflows/backend-check.yaml
backend/config/checkstyle/checkstyle.xml
scripts/build.sh

change add build.sh 

---

backend/Dockerfile
backend/config/checkstyle/checkstyle.xml

add build.sh change

---

.github/workflows/backend-check.yaml
backend/config/checkstyle/checkstyle.xml

change address ecr

---

.github/workflows/backend-check.yaml
backend/config/checkstyle/checkstyle.xml

ecr address 346011888304

---

backend/src/main/java/com/tamnara/backend/bookmark/controller/BookmarkController.java
backend/src/main/java/com/tamnara/backend/bookmark/service/BookmarkService.java
backend/src/main/java/com/tamnara/backend/bookmark/service/BookmarkServiceImpl.java

#91 
<br/>
<br/>
- 삭제 성공 시 `204 No Content`에 맞게 응답 body 제거
- 서비스에서 삭제된 북마크 ID를 반환하던 불필요한 로직 제거

[풀스택] [refactor] 북마크 해제 응답 및 서비스 로직 정리

---

backend/Dockerfile

CMD ["java", "-jar", "build/libs/backend-0.0.1-SNAPSHOT.jar"]

cd-finally

---

backend/src/main/java/com/tamnara/backend/global/health/HealthCheckController.java

heathychck

---

backend/src/main/java/com/tamnara/backend/user/dto/UserUpdateRequest.java
backend/src/test/java/com/tamnara/backend/user/controller/UserControllerIntegrationTest.java
backend/src/test/java/com/tamnara/backend/user/service/UserServiceTest.java

#60 
#124 에서 변경하거나 새로 도입한 DTO를 테스트 코드에도 적용함

refactor(user): 테스트 코드에 명시적 DTO 적용

---

backend/Dockerfile

add signoz

---

.github/workflows/backend-check.yaml
backend/Dockerfile

add curl -Lo opentelemetry-javaagent.jar

add curl -Lo opentelemetry-javaagent.jar Develop

---

.github/workflows/backend-check.yaml
backend/Dockerfile

 add curl -Lo opentelemetry-javaagent.jar

---

.github/workflows/backend-check.yaml
backend/Dockerfile

OTEL 엔드포인트 시크릿 처리

---

.github/workflows/backend-check.yaml
backend/Dockerfile

add AWS_REGION: ap-northeast-2

 add AWS_REGION: ap-northeast-2

---

.github/workflows/backend-check.yaml
backend/Dockerfile

add AWS_REGION: ap-northeast-2

add AWS_REGION: ap-northeast-2 Develop

---

.github/workflows/backend-check.yaml
backend/Dockerfile

OIDC 인증 추가

---

.github/workflows/backend-check.yaml
backend/Dockerfile

Deploy to ECS OTEL_EXPORTER_OTLP_ENDPOINT

Deploy to ECS OTEL_EXPORTER_OTLP_ENDPOINT

---

backend/src/main/java/com/tamnara/backend/global/constant/ResponseMessage.java
backend/src/test/java/com/tamnara/backend/news/config/NewsServiceMockConfig.java
backend/src/test/java/com/tamnara/backend/news/controller/NewsControllerTest.java

#72 #147
<br/>
<br/>
**경로:** `...backend/config/NewsServiceMockConfig.java` -> `...backend/news/config/NewsServiceMockConfig.java`

[풀스택] [test] 뉴스 테스트 config 파일 경로 수정 및 컨트롤러 테스트에 상수 클래스의 페이징 상수 적용

---

.github/workflows/backend-check.yaml
backend/Dockerfile
scripts/build.sh

updat ecs task defination (enviroment 에서 OTEL_EXPORTER_OTLP_ENDPOINT 제거)

updat ecs task defination

---

.github/workflows/backend-check.yaml
backend/Dockerfile

add latest

---

backend/src/main/java/com/tamnara/backend/global/config/SchedulingConfig.java

- `@EnableScheduling` 어노테이션을 활성화하여 스프링 스케줄링 기능 사용 가능하도록 설정
- `SchedulingConfig` 설정 클래스 생성
- `@Scheduled` 어노테이션을 사용하는 작업(예: 투표 통계 자동 생성)을 실행할 수 있도록 준비
---
`com.tamnara.backend.global.config.SchedulingConfig`
---
이제 원하는 클래스에 `@Scheduled(fixedRate = ...)` 또는 `@Scheduled(cron = ...)`을 붙이면 자동 실행 가능

chore: 스케줄링 기능 활성화를 위한 설정 클래스 추가

---

.github/workflows/dev-deploy.yaml

OTEL Java Agent 다운로드 코드 위치 수정

---

.github/workflows/dev-deploy.yaml

ci - 이미지 테그 수정

---

.github/workflows/dev-deploy.yaml

dev-deploy.sh 파일 복사 과정 추가

---

.github/workflows/dev-deploy.yaml

deploy.sh 설정 수정

---

.github/workflows/dev-deploy.yaml
backend/Dockerfile

docker file 수정
COPY scripts/dev-deploy.sh /app/dev-deploy.sh
RUN chmod +x /app/dev-deploy.sh

docker file 수정

---

.github/workflows/dev-deploy.yaml
backend/Dockerfile

ssh 스크립트 변경

---

backend/Dockerfile

Duser.timezone=Asia/Seoul에 \ 추가 ->  -Duser.timezone=Asia/Seoul \

Duser.timezone=Asia/Seoul에 \ 추가 ->  -Duser.timezone=Asia/Seoul \

---

.github/workflows/dev-deploy.yaml

sudo docker ps -a -q --filter name=dev-backend | grep -q . && sudo docker rm -f dev-backend

# 🔥 실행 중이든 종료됐든, 이름 dev-backend인 건 무조건 지운다

---

scripts/build.sh

-build-arg ECR_URI_DEV= add in build.sh

-build-arg ECR_URI_DEV= add in build.sh

---

.github/workflows/dev-deploy.yaml

 OTEL_SERVICE_NAME dev/prod 분리

---

backend/src/main/java/com/tamnara/backend/poll/service/PollSchedulerServiceImpl.java
backend/src/main/java/com/tamnara/backend/poll/service/PollServiceImpl.java
backend/src/main/java/com/tamnara/backend/poll/service/VoteServiceImpl.java

<br/>
<br/>
- `@Override` 추가
- `@Transactional` 제거
- `@Override`, `@Async` 추가

fix: 누락된 어노테이션 추가

---

.github/workflows/dev-deploy.yaml

 redis 설정 비번 없음

---

.github/workflows/dev-deploy.yaml

테스트코드 빌드시 실행

---

.github/workflows/backend-check.yaml
backend/Dockerfile

레디스 연동 prod & 빌드시 테스트 실행

---

.github/workflows/dev-deploy.yaml

빌드시 테스트 실행

---

.github/workflows/dev-deploy.yaml

SPRING_PROFILES_ACTIVE: test 추가

SPRING_PROFILES_ACTIVE: test 추가

---

.github/workflows/dev-deploy.yaml

runs-on: ubuntu-22.04

---

backend/src/test/java/com/tamnara/backend/auth/controller/KakaoControllerIntegrationTest.java

test 파일 ci test 에서 디비에 유 저가 없어서 에러 발생 -> BeforeEach 추가

 test 파일 ci test 에서 디비에 유 저가 없어서 에러 발생 -> BeforeEach 추가

---

backend/src/test/java/com/tamnara/backend/auth/controller/KakaoControllerIntegrationTest.java

testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine' 추가

testImplementation 'org.junit.jupiter:junit-jupiter-api'

---

backend/src/test/java/com/tamnara/backend/auth/controller/KakaoControllerIntegrationTest.java

userRepository.deleteAll(); 추가

 userRepository.deleteAll(); 추가

---

backend/src/test/java/com/tamnara/backend/auth/controller/KakaoControllerIntegrationTest.java

 add role,state in BeforeEach

---

backend/src/test/java/com/tamnara/backend/auth/controller/KakaoControllerIntegrationTest.java

@Transactional 추가

---

backend/src/test/java/com/tamnara/backend/auth/controller/KakaoControllerIntegrationTest.java

userRepository.flush();추가

---

backend/src/test/java/com/tamnara/backend/auth/controller/KakaoControllerIntegrationTest.java

트랜잭션 위치 변경

---

backend/src/test/java/com/tamnara/backend/auth/controller/KakaoControllerIntegrationTest.java

kakaoclient delete

---

backend/src/test/java/com/tamnara/backend/auth/controller/KakaoControllerIntegrationTest.java

import com.tamnara.backend.auth.jwt.JwtProvider;  추가

import com.tamnara.backend.auth.jwt.JwtProvider;

---

.github/workflows/backend-check.yaml
.github/workflows/dev-deploy.yaml
backend/Dockerfile

reids 설정 수정

---

.github/workflows/dev-deploy.yaml

tamnara-network 중복 -> 삭제 완료

---

.github/workflows/dev-deploy.yaml

띄어쓰기 에러 수정

---

backend/src/main/java/com/tamnara/backend/poll/service/PollSchedulerServiceImpl.java
backend/src/main/java/com/tamnara/backend/poll/service/PollServiceImpl.java

#481 
<br/>
<br/>
- **작업한 파일**
- `poll/service/PollServiceImpl`
- `poll/service/SchedulerServiceImpl
- **작업 내용:** 로깅 추가

feat: 투표 기능의 서비스 로직에 로깅 추가
