100-hours-a-week/18-team-timeline-be

- .github/workflows/backend-check.yaml
- .idea/gradle.xml
- .idea/jarRepositories.xml
- backend/build.gradle
- backend/config/checkstyle/checkstyle.xml
- backend/src/main/resources/application.properties
feat/common-config -> develop
- 깃허브 트리거에 따른 작업 자동화 파일 추가
- `application.properties`: 시간 타입 직렬화/역직렬화 시 기본 타임존을 UTC로 변경
> chore: 클라우드 작업 자동화 파일 추가, 시간 타입 기본 타임존 변경

- backend/src/main/java/com/tamnara/backend/global/config/SecurityConfig.java
> chore: SecurityConfig에 CORS 설정 및 JWT 인증 필터 등록

- backend/src/main/java/com/tamnara/backend/global/jwt/JwtProvider.java
- backend/src/main/java/com/tamnara/backend/user/controller/UserController.java
- backend/src/main/java/com/tamnara/backend/user/dto/UserEmailCheckResponseDto.java
- backend/src/main/java/com/tamnara/backend/user/dto/UserInfoResponseDto.java
- backend/src/main/java/com/tamnara/backend/user/service/KakaoService.java
- backend/src/main/java/com/tamnara/backend/user/service/UserService.java
메서드 | URL | 설명
-- | -- | --
GET | `/users/me` | 현재 로그인한 사용자의 정보를 반환 (토큰 기반 인증 필요)
POST | `/users/logout` | 클라이언트 측 토큰 삭제용 로그아웃 요청 처리 (토큰 기반 인증 필요)
GET | `/users/check-email?email={email}` | 이메일 중복 여부 확인
GET | `/users/check-nickname?nickname={nickname}` | 닉네임 중복 여부 확인
---
모든 보호된 API는 JWT 기반 인증 필터(JwtAuthenticationFilter)를 통해 유효한 토큰이 있는지 확인
Swagger에서도 Authorize → Bearer {access_token} 방식으로 테스트 가능
Swagger API 문서에는 @SecurityRequirement(name = "bearerAuth")로 인증 필요 여부 명시
---
- ✅ Postman에서 토큰 발급 및 인증 API (`/users/me`) 테스트 완료
- ✅ Swagger UI에서 `Authorize → Bearer {token}` 입력 후 인증 API 정상 호출 확인
---
카카오 로그인 후 JWT access token은 보안상 응답 바디에 포함하지 않고 응답 헤더(Authorization)에 포함됩니다.
Swagger나 Postman에서는 Authorization 헤더 확인이 가능하지만,
브라우저에서 직접 호출 시 CORS 정책상 브라우저에서 응답 헤더를 읽을 수 없습니다.
따라서 현재는 디버깅을 위해 access token을 …
> feat: 회원정보조회, 로그아웃, 이메일/닉네임 중복조회 api 추가

- backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
- backend/src/main/java/com/tamnara/backend/news/repository/NewsImageRepository.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
1. `[NewsController.java`의 `findHotissueNews()` 의 응답 객체
`data: Map.of("newsList", newsCards)` 로 감싸서 반환 → API 명세서에 작성된 대로 `data = []` 형태로 프론트에 반환할 수 있음
```java
List<NewsCardDTO> newsCards = newsService.getNewsCardPage(...);
// 이전
return ResponseEntity.ok(Map.of(
"success", true,
"message", "요청하신 데이터를 성공적으로 불러왔습니다.",
"data", newsCards   // ✅ 여기서 직접 배열을 반환함
)
//수정 후
return ResponseEntity.ok(Map.of(
"success", true,
"message", "요청하신 데이터를 성공적으로 불러왔습니다.",
"data", Map.of("newsList", newsCards)
));
```
1. `newsImageRepository.java` 의 `findByNewsId`
- 하나의 news id에 대해서 실수로 여러 개의 이미지가 들어갈 경우, `findByNewsId`를 사용하면 서버 에러 → `findFirstByNewsIdOrderByIdAsc`를 사용하여 아이디가 가장 빠른 이미지 하나만 가져오게 함
```java
// NewsImageRepository.java
// 이전
Optional<NewsImage> findByNewsId(Long newsId);
// 수정 후
Optional<NewsImage> …
```
> update: 핫이슈 뉴스 응답 구조 수정 및 이미지 필드 네이밍 통일, 중복 이미지 대응

- backend/src/main/java/com/tamnara/backend/global/config/SecurityConfig.java
- backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
- backend/src/main/java/com/tamnara/backend/news/dto/NewsCardDTO.java
- backend/src/main/java/com/tamnara/backend/news/repository/NewsRepository.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsService.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
#2 #8 #11 
<br/>
<br/>
- 뉴스 컨트롤러에서 응답 data의 내부 배열 필드명을 newsList로 수정
`/news/controller/NewsController`
```java
Map<String, Object> newsList = Map.of("newsList", newsCards);
return ResponseEntity.ok(Map.of(
"success", true,
"message", "요청하신 데이터를 성공적으로 불러왔습니다.",
"data", newsList
));
```            
- NewsCardDTO의 이미지 속성명을 수정: `imageUrl` -> `image`
`/news/dto/NewsCardDTO`
<br/>
`/news/repository/NewsRepository`
- 전체 뉴스 조회 시, 핫이슈와 일반 뉴스 조회 메서드 분리 및 핫이슈 조회 시 `id ASC` 정렬 추가
```java
Page<News> findAllByIsHotissueTrueOrderByIdAsc(Pageable pageable);
Page<News> findByIsHotissueFalseOrderByUpdatedAtDescIdDesc(Pageable pageable);
```
- 카테고리 별 일반 뉴스 조회 메서드의 매개변수에서 핫이슈 여부 변수(`isHotissue`) 제거 및 메서드명 수정
```java
@Query("""
SELECT n FROM News n
WHERE n.isHotissue = false
AND (
(:categoryId IS NULL AND …
```
> feat: API 명세서와의 불일치 수정 및 핫이슈/일반 뉴스 조회 로직 분리

- backend/build.gradle
- backend/src/main/java/com/tamnara/backend/global/config/WebClientConfig.java
- backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
- backend/src/main/java/com/tamnara/backend/news/dto/NewsCardDTO.java
- backend/src/main/java/com/tamnara/backend/news/dto/TimelineCardDTO.java
- backend/src/main/java/com/tamnara/backend/news/dto/WrappedDTO.java
- backend/src/main/java/com/tamnara/backend/news/dto/request/AINewsRequest.java
- backend/src/main/java/com/tamnara/backend/news/dto/response/AINewsResponse.java
- backend/src/main/java/com/tamnara/backend/news/dto/response/NewsDetailResponse.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
#33 #34 #35
<br/>
<br/>
- 길이 제한 관련 로직에 대해 추가 수정 필요
- DB 컬럼의 길이 제한을 255로 연장
- 응답을 길이 제한만큼 자르는 로직 제거
> fix: 뉴스 생성/업데이트 API 연동 테스트 완료

- backend/src/main/java/com/tamnara/backend/global/config/WebClientConfig.java
- backend/src/main/java/com/tamnara/backend/news/domain/News.java
- backend/src/main/java/com/tamnara/backend/news/domain/TimelineCard.java
- backend/src/main/java/com/tamnara/backend/news/dto/response/AINewsResponse.java
- backend/src/main/java/com/tamnara/backend/news/dto/response/NewsDetailResponse.java
- backend/src/main/java/com/tamnara/backend/news/repository/NewsImageRepository.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
- backend/src/main/resources/application.properties
- backend/src/test/java/com/tamnara/backend/news/RepositoryTest/NewsImageRepositoryTest.java
#37 #38 #39 
<br/>
<br/>
`application.properties`, `/global/config/WebCilentConfig`
- DB
- `DB_URL`
-  `DB_USERNAME`
- `DB_PASSWORD`
- AI
- `AI_BASE_URL`
<br/>
`/news/domain/News`, `/news/domain/TimelineCard`
- News
- `title`: 24 -> 255
- `summary`: 36 -> 255 
- TimelineCard
- `title`: 18 -> 255 
`/news/service/NewsServiceImpl`
- `substring()`으로 길이 제한만큼 자르는 로직 제거
<br/>
`/news/dto/response/NewsDetailResponse`
- 이미지 필드 추가: `image`
`/news/dto/response/AINewsResponse`
- 이미지 필드명 수정: `imageUrl` -> `image`
`/news/repository/NewsImageRepository`
- `findByNewsId()` 반환 타입 변경: `Optional<NewsImage>` -> `NewsImage`
`/news/service/NewsServiceImpl`
- 뉴스 생성 로직에 뉴스 이미지 저장 로직 추가
- 뉴스 업데이트 로직에 기존 뉴스 이미지 삭제 및 새로운 뉴스 이미지 저장 로직 추가
- 뉴스 이미지를 조회할 경우 이미지가 존재할 경우 URL을, 존재하지 않을 경우 null 반환 로직 추가
> fix: DB 설정 및 AI URL 환경변수화, 문자열 길이 제한 완화 및 이미지 필드 처리 수정

- backend/src/main/java/com/tamnara/backend/news/dto/request/AITimelineMergeRequest.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
> [풀스택] [fix] AI에 타임라인 병합 요청 시, 실패하거나 응답이 부적절하게 나오는 문제 해결

- backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsService.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
#57 
<br/>
<br/>
- 카테고리별 추가 로딩 시, '전체(ALL)' 카테고리를 조회하고 싶은 경우 쿼리 파라미터 `category="ALL"`로 명시
- 카테고리별 추가 로딩 시, '기타(ECT)' 카테고리를 조회하고 싶은 경우 쿼리 파라미터 `category=null` 명시 또는 `category` 생략
> fix: '전체' 카테고리의 뉴스 카드 추가 로딩 로직 추가

- backend/src/main/java/com/tamnara/backend/global/config/SecurityConfig.java
이메일 중복조회, 닉네임 중복조회 엔드포인트를 permitAll()에 추가하여 API 사용이 가능하게 함.
관련 이슈
#67
> fix: 이메일/닉네임 중복조회 CORS 허용

- backend/src/main/java/com/tamnara/backend/global/exception/AIException.java
- backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
- backend/src/main/java/com/tamnara/backend/news/repository/NewsImageRepository.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsService.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
#70 #75 #91 #92
<br/>
- 기타
<br/>
- AI API 요청 시 4xx 또는 5xx 응답이 반환될 경우 AIException으로 래핑하여 통일된 예외 구조 유지
- AI API가 반환한 `message` 필드를 예외 메시지로 사용하여 디버깅 용이성 증가
- WebClient의 `.onStatus()`를 통해 예외 body를 파싱하여 처리
- 타임라인 생성 외부 API에서 `404 Not Found` 응답이 오는 경우, `204 No Content`를 반환하여 사용자 기능 흐름이 중단되지 않도록 개선
<br/>
- 뉴스 이미지 조회 리포지토리 메서드 `findByNewsId()`의 반환 타입에 `Optional<T>` 적용하여 NPE 방지 및 후속 로직에서 명시적으로 처리
- 리포지토리 메서드의 변경 내용을 서비스 로직에 적용하여 정리
```java
Optional<NewsImage> newsImage = newsImageRepository.findByNewsId(news.getId());
String image = newsImage.map(NewsImage::getUrl).orElse(null);
```
- 이외 뉴스 기능, 댓글 기능, 북마크 기능에서 단건 조회 메서드의 반환 타입에 `Optional<T>`이 적용된 상태 확인
<br/>
- 삭제 성공 시 `204 No Content`에 맞게 응답 body 제거
- 서비스에서 삭제된 뉴스 ID를 반환하던 불필요한 로직 제거
<br/>
- 문제: 1달 카드가 생성되는 즉시 삭제되어 생성된 뉴스에 타임라인 카드가 존재하지 않거나 부족한 경우 …
> [풀스택] [fix] 뉴스 관련 로직 및 예외 처리 개선 및 타임라인 병합 조건 수정

- backend/src/main/java/com/tamnara/backend/comment/controller/CommentController.java
- backend/src/main/java/com/tamnara/backend/comment/service/CommentService.java
- backend/src/main/java/com/tamnara/backend/comment/service/CommentServiceImpl.java
#91 
<br/>
<br/>
- 삭제 성공 시 `204 No Content`에 맞게 응답 body 제거
- 서비스에서 삭제된 댓글 ID를 반환하던 불필요한 로직 제거
> [풀스택] [refactor] 댓글 삭제 응답 및 서비스 로직 정리

- backend/src/main/java/com/tamnara/backend/comment/controller/CommentController.java
- backend/src/main/java/com/tamnara/backend/comment/dto/CommentDTO.java
- backend/src/main/java/com/tamnara/backend/comment/dto/CommentListResponse.java
- backend/src/main/java/com/tamnara/backend/comment/dto/request/CommentCreateRequest.java
- backend/src/main/java/com/tamnara/backend/comment/dto/response/CommentCreateResponse.java
- backend/src/main/java/com/tamnara/backend/comment/dto/response/CommentListResponse.java
- backend/src/main/java/com/tamnara/backend/comment/service/CommentService.java
- backend/src/main/java/com/tamnara/backend/comment/service/CommentServiceImpl.java
- backend/src/main/java/com/tamnara/backend/global/dto/WrappedDTO.java
- backend/src/main/java/com/tamnara/backend/global/exception/GlobalExceptionHandler.java
Closes #98
<br/>
<br/>
- `WrappedDTO<T>`: 공통 응답 구조 DTO로, T는 데이터 필드의 타입을 의미
- `CommentListResponse`: 댓글 목록 응답 DTO
- `CommentCreateResponse`: 댓글 생성 응답 DTO
- 댓글 목록 조회: `ResponseEntity<WrappedDTO<CommentListResponse>>` - `200 Ok`
- 댓글 생성: `ResponseEntity<WrappedDTO<CommentCreateResponse>>` - `201 Created`
- 댓글 삭제: `ResponseEntity<WrappedDTO<Void>>` - `204 No Content`
```json
{
"success": true,
"message": "댓글이 성공적으로 생성되었습니다.",
"data": {
"commentId": 49
}
}
```
```json
{
"success": false,
"message": "인증되지 않은 사용자입니다."
}
```
> [풀스택] [refactor] 댓글 API 응답에 DTO 적용

- backend/src/main/java/com/tamnara/backend/bookmark/controller/BookmarkController.java
- backend/src/main/java/com/tamnara/backend/bookmark/dto/response/BookmarkAddResponse.java
- backend/src/main/java/com/tamnara/backend/global/dto/WrappedDTO.java
- backend/src/main/java/com/tamnara/backend/global/exception/GlobalExceptionHandler.java
Closes #99
<br/>
<br/>
- `WrappedDTO<T>`: 공통 응답 구조 DTO로, T는 데이터 필드의 타입을 의미
- `BookmarkAddResponse`: 북마크 추가 응답 DTO
- 북마크 추가: `ResponseEntity<WrappedDTO<BookmarkAddResponse>>` - `201 Created`
- 북마크 삭제: `ResponseEntity<WrappedDTO<Void>>` - `204 No Content`
```json
{
"success": true,
"message": "북마크가 성공적으로 추가되었습니다.",
"data": {
"bookmarkId": 49
}
}
```
```json
{
"success": false,
"message": "이미 북마크가 추가된 상태입니다."
}
```
> [풀스택] [refactor] 북마크 API 응답에 DTO 적용

- backend/src/main/java/com/tamnara/backend/BackendApplication.java
- backend/src/main/java/com/tamnara/backend/global/exception/AIException.java
- backend/src/main/java/com/tamnara/backend/news/service/AsyncAIService.java
- backend/src/main/java/com/tamnara/backend/news/service/AsyncAIServiceImpl.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
Closes #69 
<br/>
<br/>
- @EnableAsync를 메인 애플리케이션 클래스에 적용하여 Spring 비동기 처리 기능을 활성화
<br/>
- `/news/service/AsyncAIService`, `/news/service/AsyncAIServiceImpl`, 
- 기존 뉴스 생성/업데이트 로직에서 호출하던 여론 통계 생성 API 요청을 AsyncAIService를 통해 비동기로 분리
- AI API가 `404 Not Found` 응답을 반환할 경우 null로 반환되도록 처리
<br/>
- AsyncAIService의 여론 통계 생성 API 요청 메서드를 비동기로 호출
- API 요청 메서드의 응답이 null일 경우 여론 통계 저장 로직 생략
- 뉴스 생성 시: 긍정, 중립, 부정을 모두 0으로 저장
- 뉴스 업데이트 시: 기존 여론 통계 유지
- 모든 AI 관련 비동기 응답을 수신한 후 통합 저장이 진행되도록 조정하여 데이터의 원자성과 트랜잭션 일관성 유지
<br/>
**조건:** 동일한 요청 키워드(SKT, 유심), 동일한 기간(30일)
- 동기적 처리 시 뉴스 생성 처리 시간
1. 115235ms
2. 141151ms
3. 123482ms
- 비동기 처리 후 뉴스 생성 처리 시간
1. 88457ms
2. 99878ms
3. 87038ms
**⇒ 개선된 속도: 약 38.34% 단축**
> [풀스택] [refactor] 뉴스 생성/업데이트 로직에서 여론 통계 생성 API 요청을 비동기 처리

- backend/src/main/java/com/tamnara/backend/bookmark/constant/BookmarkResponseMessage.java
- backend/src/main/java/com/tamnara/backend/bookmark/controller/BookmarkController.java
- backend/src/main/java/com/tamnara/backend/bookmark/service/BookmarkServiceImpl.java
- backend/src/main/java/com/tamnara/backend/global/constant/ResponseMessage.java
closes #139
<br/>
<br/>
- 작업 파일: `bookmark.constant.BookmarkResponseMessage`, `bookmark.service.BookmarkServiceImpl`, `bookmark.controller.BookmarkController`
- 북마크 추가 성공 메시지: `BOOKMARK_ADDED_SUCCESS`
- 북마크 예외 메시지
- 북마크가 이미 추가된 경우: `BOOKMARK_ALREADY_ADDED`
- 북마크가 존재하지 않는 경우: `BOOKMARK_NOT_FOUND`
- `@Autowired` 등의 어노테이션을 적용하여 빈에 주입하지 않는다.
- `BookmarkResponseMessage.BOOKMARK_XXX`처럼 static 접근하여 활용한다.
> [풀스택] [refactor] 북마크 응답 메시지를 bookmark 패키지의 상수 클래스에 정의

- backend/src/main/java/com/tamnara/backend/comment/constant/CommentResponseMessage.java
- backend/src/main/java/com/tamnara/backend/comment/controller/CommentController.java
- backend/src/main/java/com/tamnara/backend/comment/service/CommentServiceImpl.java
- backend/src/main/java/com/tamnara/backend/global/constant/ResponseMessage.java
closes #138
<br/>
<br/>
- 작업 파일: `comment.constant.CommentResponseMessage`, `comment.service.CommentServiceImpl`, `comment.controller.CommentController`
- 댓글 목록 조회 성공 메시지: `COMMENT_LIST_FETCH_SUCCESS`
- 댓글 생성 성공 메시지: `COMMENT_CREATED_SUCCESS`
- 댓글 예외 메시지
- 댓글이 존재하지 않는 경우: `COMMENT_NOT_FOUND`
- 댓글을 삭제할 권한이 없는 경우: `COMMENT_DELETE_FORBIDDEN`
- `@Autowired` 등의 어노테이션을 적용하여 빈에 주입하지 않는다.
- `CommentResponseMessage.COMMENT_XXX`처럼 static 접근하여 활용한다.
> [풀스택] [refactor] 댓글 응답 메시지를 comment 패키지의 상수 클래스에 정의

- backend/src/main/java/com/tamnara/backend/user/controller/UserController.java
- backend/src/main/java/com/tamnara/backend/user/dto/UserInfoWrapper.java
- `GET /users/me` API의 응답 본문을 `UserInfo` → `UserInfoWrapper`로 감쌈
- 추후 확장성을 고려해 `user` 필드로 감싼 형태로 반환
- 응답 일관성을 위해 다른 API들과 포맷을 맞춤 (`WrappedDTO<Wrapper>` 구조)
- 새로운 래퍼 클래스 `UserInfoWrapper` 생성: `record UserInfoWrapper(UserInfo user)`
- 내부적으로 `UserInfo` 조회 로직은 그대로 유지 (`userService.getCurrentUserInfo()`)
- 변경된 네이밍 적용: `UserUpdateRequestDto` → `UserUpdateRequest`
- 응답 포맷을 통일하여 프론트엔드 파싱 편의성 및 추후 필드 확장 시 유연성 확보
- 기존 WrappedDTO<UserInfo> 형태에서 WrappedDTO<UserInfoWrapper>로 변경됨에 따라 JSON 응답 구조가 `{ user: { ... } }` 형식으로 변경됨
- 클라이언트는 `/users/me` API 응답에서 `user`라는 키로 유저 정보를 접근해야 함
- 기존 `UserInfo` 내부 필드는 변경 없음
> refactor: 응답 DTO 포맷 통일을 위한 UserInfoWrapper 적용, UserUpdateRequest 이름 변경 적용

- backend/src/main/java/com/tamnara/backend/global/config/RestTemplateConfig.java
외부 API 통신에 사용할 수 있도록 `RestTemplate`을 Spring Bean으로 등록하는 `RestTemplateConfig`를 추가했습니다.
- `global.config` 패키지에 `RestTemplateConfig` 클래스 생성
- `@Bean` 애너테이션을 통해 `RestTemplate`을 컨테이너에 등록
`RestTemplate`을 직접 생성하지 않고 Bean으로 등록함으로써:
- 서비스 단에서 재사용 가능
- 테스트 시 Mock 주입 용이
- 타임아웃, 인터셉터 등 중앙 집중 설정 가능
- `KakaoApiClient` 등 외부 API 연동 서비스에서 DI 방식으로 사용하기 위함
> feat: RestTemplate Bean 등록을 위한 RestTemplateConfig 추가

- backend/src/main/java/com/tamnara/backend/user/constant/UserResponseMessage.java
- backend/src/main/java/com/tamnara/backend/user/controller/UserController.java
- backend/src/main/java/com/tamnara/backend/user/service/UserService.java
#161 
- `UserResponseMessage` 클래스 추가: 사용자 관련 메시지를 상수로 관리
- `UserController`, `UserService` 내 문자열 하드코딩 제거
- 이메일/닉네임 유효성 검증, 회원 정보 조회/수정, 로그아웃, 회원가입 응답 등
- 공통 메시지(`INTERNAL_SERVER_ERROR`, `USER_NOT_FOUND` 등)는 `global.constant.ResponseMessage`에서 가져오도록 유지
- 응답 메시지를 중앙 집중식 관리하여 유지보수 용이
- 하드코딩 문자열 제거로 오타 및 중복 방지
- 메시지 일관성 확보로 API 응답 신뢰도 향상
> refactor: 회원 기능 응답 메시지 상수화 및 하드코딩 제거

- backend/src/main/java/com/tamnara/backend/user/constant/UserResponseMessage.java
- backend/src/main/java/com/tamnara/backend/user/controller/UserController.java
- backend/src/main/java/com/tamnara/backend/user/exception/DuplicateEmailException.java
- backend/src/main/java/com/tamnara/backend/user/exception/DuplicateUsernameException.java
- backend/src/main/java/com/tamnara/backend/user/exception/InactiveUserException.java
- backend/src/main/java/com/tamnara/backend/user/exception/UserNotFoundException.java
- backend/src/main/java/com/tamnara/backend/user/service/UserService.java
- backend/src/test/java/com/tamnara/backend/user/controller/UserControllerIntegrationTest.java
- backend/src/test/java/com/tamnara/backend/user/service/UserServiceTest.java
#175 
- 예외 메시지 상수화
- 중복된 하드코딩 메시지를 제거하고 `UserResponseMessage` 클래스로 통합
- 오타 수정 (`EMAIL_UNAVALIABLE` → `EMAIL_UNAVAILABLE` 등)
- 회원 상태 검증 강화
- 비활성(탈퇴) 회원에 대해:
- 회원 정보 조회, 수정, 탈퇴, 로그아웃 시 `403 Forbidden` 응답 처리 추가
- 관련 서비스 로직에서 `InactiveUserException`을 명시적으로 던지도록 리팩토링
- 예외 클래스 메시지 통합
- `DuplicateEmailException`, `DuplicateUsernameException`, `InactiveUserException`, `UserNotFoundException` 생성자에 메시지 상수 적용
- `Controller `리팩토링
- 상태 코드 및 메시지 응답 일관성 유지 (INVALID_TOKEN, ACCOUNT_FORBIDDEN 등)
- Swagger 문서에 401, 403, 404, 409 응답 명시 추가
- 통합 테스트 강화
- 비활성 회원이 API를 호출하는 경우 403을 반환하는 테스트 추가
- `GET /users/me`
- `PATCH /users/me`
- 기존 메시지에 상수 사용 적용 (`EMAIL_UNAVAILABLE`, `NICKNAME_UNAVAILABLE`, `ACCOUNT_FORBIDDEN` 등)
- 모든 통합 테스트 및 단위 테스트 통과 확인
- 실제 비활성 상태에서의 접근 차단 여부 확인 완료
- 프론트엔드에서는 해당 메시지(`ACCOUNT_FORBIDDEN`, …
> refactor: 회원 기능 예외 처리 및 메시지 통합 개선

- backend/src/main/java/com/tamnara/backend/global/constant/ResponseMessage.java
- backend/src/main/java/com/tamnara/backend/user/constant/UserResponseMessage.java
- backend/src/main/java/com/tamnara/backend/user/controller/UserController.java
- backend/src/main/java/com/tamnara/backend/user/exception/InactiveUserException.java
- backend/src/test/java/com/tamnara/backend/user/controller/UserControllerIntegrationTest.java
##회원 응답 메시지 상수 통합 및 컨트롤러 수정
- `INVALID_TOKEN`, `ACCOUNT_FORBIDDEN` 상수를
`UserResponseMessage` → `ResponseMessage`로 이동하여 전역 메시지로 통합
- 기존 UserController 및 예외 클래스에서 해당 상수 사용 시 import 경로 수정
- 관련 테스트 코드(UserControllerIntegrationTest)에도 변경 사항 반영
- 동일한 메시지가 여러 도메인(user, auth)에서 중복 정의되고 있어 관리 일관성 확보를 위해 전역 상수로 분리
- 메시지 관리 책임을 `ResponseMessage`로 집중시켜 유지보수 편의성 향상
- `UserControllerIntegrationTest` 실행 완료
- 모든 관련 케이스에서 응답 메시지가 정상적으로 출력됨을 확인
> refactor: 회원 응답 메시지 상수 통합 및 컨트롤러 수정

- backend/src/main/java/com/tamnara/backend/bookmark/constant/BookmarkResponseMessage.java
- backend/src/main/java/com/tamnara/backend/bookmark/constant/BookmarkServiceConstant.java
- backend/src/main/java/com/tamnara/backend/bookmark/controller/BookmarkListController.java
- backend/src/main/java/com/tamnara/backend/bookmark/domain/Bookmark.java
- backend/src/main/java/com/tamnara/backend/bookmark/dto/response/BookmarkListResponse.java
- backend/src/main/java/com/tamnara/backend/bookmark/repository/BookmarkRepository.java
- backend/src/main/java/com/tamnara/backend/bookmark/service/BookmarkService.java
- backend/src/main/java/com/tamnara/backend/bookmark/service/BookmarkServiceImpl.java
- backend/src/main/java/com/tamnara/backend/news/domain/News.java
- backend/src/main/java/com/tamnara/backend/news/domain/NewsImage.java
- backend/src/main/java/com/tamnara/backend/news/domain/NewsTag.java
- backend/src/main/java/com/tamnara/backend/news/domain/Tag.java
- backend/src/main/java/com/tamnara/backend/news/domain/TimelineCard.java
- backend/src/main/java/com/tamnara/backend/news/dto/NewsCardDTO.java
- backend/src/main/java/com/tamnara/backend/news/repository/CategoryRepository.java
- backend/src/main/java/com/tamnara/backend/news/repository/NewsRepository.java
- backend/src/main/java/com/tamnara/backend/news/repository/NewsTagRepository.java
- backend/src/main/java/com/tamnara/backend/news/repository/TagRepository.java
- backend/src/main/java/com/tamnara/backend/news/repository/TimelineCardRepository.java
- backend/src/main/java/com/tamnara/backend/news/util/ValueOfEnum.java
- backend/src/main/java/com/tamnara/backend/news/util/ValueOfEnumValidator.java
- backend/src/test/java/com/tamnara/backend/bookmark/controller/BookmarkListControllerTest.java
- backend/src/test/java/com/tamnara/backend/bookmark/repository/BookmarkRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/bookmark/service/BookmarkServiceImplTest.java
closes #210
<br/>
<br/>
```java
Page<Bookmark> findByUser(User user, Pageable pageable);
```
- 북마크 리포지토리 테스트 추가
- 회원으로 북마크 목록 조회 검증
- 북마크 테이블의 `createdAt` 기준 내림차순 정렬 적용 검증
- 북마크 상수 클래스 `BookmarkServiceConstant` 추가 및 페이징 상수 `PAGE_SIZE` 정의
<br/>
```java
BookmarkListResponse getBookmarkedNewsList(Long userId, Integer offset);
```
- 북마크 목록을 불러오고, 북마크의 뉴스를 응답의 `bookmarks` 필드에 저장하여 페이징 필드 `offset`, `hasNext` 반환
- 북마크한 뉴스가 존재하지 않을 경우, 건너뛰기 -> 뉴스 카드 목록이 페이징 개수에 도달되지 않을 수 있다.
- 응답용 DTO `BookmarkListResponse` 추가
- 북마크한 뉴스 카드 목록 조회 서비스 검증
- 회원이 북마크한 뉴스 카드 목록 조회 검증
- 북마크한 뉴스 카드 목록 조회 시 회원이 존재하지 않으면 예외 처리 검증
<br/>
- 북마크 목록 조회 컨트롤러 추가: `news.controller.BookmarkListController`
- 북마크 목록 조회 API(`/user/me/bookmarks`) 추가
```java
@GetMapping
public ResponseEntity<WrappedDTO<BookmarkListResponse>> …
```
> [풀스택] [feat] 북마크한 뉴스 카드 목록 조회 기능 구현

- backend/src/main/java/com/tamnara/backend/news/repository/NewsTagRepository.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
- backend/src/test/java/com/tamnara/backend/news/repository/NewsTagRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/service/NewsServiceImplTest.java
#211 
<br/>
<br/>
- **작업한 파일:** `news.repository.NewsTagRepository`
- **작업한 내용:** 입력받은 키워드 목록과 태그 목록이 일치하는 뉴스를 반환하는 리포지토리 메서드 추가
- **테스트 목록**
- 입력 키워드 목록과 일치하는 뉴스 조회 성공 검증
- 입력 키워드 목록의 정렬 순서가 바뀌어도 동일한 결과 출력 확인
- 입력 키워드 목록과 일치하는 뉴스가 없는 경우 조회 검증 추가
<br/>
- **작업한 파일:** `news.service.NewsServiceImpl`
- **작업한 내용:** 뉴스 생성 전, 입력받은 키워드 목록과 태그 목록이 일치하는 뉴스가 존재하면 업데이트하는 선행 로직 추가
- **테스트 목록**
- 뉴스 생성 로직 내 선행 조건 분기 테스트
- 기존 뉴스가 존재하지 않을 시 `save()` 로직 처리 검증
- 기존 뉴스가 존재할 시 `update()` 호출 검증
> feat: 뉴스 생성 서비스 로직 보완

- backend/src/main/java/com/tamnara/backend/news/repository/NewsRepository.java
- backend/src/main/java/com/tamnara/backend/news/repository/NewsTagRepository.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
- backend/src/test/java/com/tamnara/backend/news/repository/NewsRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/repository/NewsTagRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/service/NewsServiceImplTest.java
#211 
<br/>
<br/>
- 리포지토리 메서드 경로 변경: `news.repository.NewsTagRepository` -> `news.repository.NewsRepository`
> refactor: 입력 키워드 목록과 태그 목록이 일치하는 뉴스 조회 메서드의 경로 변경

- backend/src/main/java/com/tamnara/backend/global/constant/ResponseMessage.java
- backend/src/main/java/com/tamnara/backend/global/exception/GlobalExceptionHandler.java
- backend/src/main/java/com/tamnara/backend/global/exception/SecurityExceptionHandler.java
- `SecurityExceptionHandler` 클래스 신설
- `AuthenticationException` → 401 Unauthorized + "유효하지 않은 토큰입니다." 반환
- `AccessDeniedException` → 401 Unauthorized + "해당 요청에 대한 접근 권한이 없습니다." 반환
- 기존 `GlobalExceptionHandler`에서 인증 관련 예외 제거 및 정리
- `DuplicateUsernameException`, `DuplicateEmailException`, `IllegalArgumentException`, `MethodArgumentNotValidException` 등 일반 예외 처리 유지
- 내부 서버 오류에 대한 응답 형식을 통일 (`WrappedDTO` 사용)
- 응답 메시지 상수화
- ResponseMessage.java에 USER_UNAUTHORIZED, INVALID_TOKEN 메시지 추가
- 인증(Authentication)과 인가(Authorization)를 명확히 구분하여 예외 처리 구조를 개선
- 클라이언트가 에러 원인을 정확히 파악할 수 있도록 HTTP 상태코드와 메시지 일관성 확보
- 예외 응답 포맷(WrappedDTO) 통일을 통해 프론트엔드 에러 처리 코드 간소화
- 토큰 누락/만료/변조 → 401 + "유효하지 않은 토큰입니다."
- 로그인은 되었지만 권한이 부족한 경우 → 401 + "해당 요청에 대한 접근 권한이 없습니다."
- 유효하지 않은 파라미터 → 400 + "잘못된 요청입니다."
- 중복 닉네임/이메일 → 409 + …
> refactor: 인증/인가 예외 처리 분리 및 응답 메시지 개선

- .gitignore
- backend/build.gradle
- backend/src/main/java/com/tamnara/backend/global/config/QuerydslConfig.java
- backend/src/main/java/com/tamnara/backend/news/constant/NewsResponseMessage.java
- backend/src/main/java/com/tamnara/backend/news/constant/NewsServiceConstant.java
- backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
- backend/src/main/java/com/tamnara/backend/news/repository/NewsRepository.java
- backend/src/main/java/com/tamnara/backend/news/repository/NewsSearchRepository.java
- backend/src/main/java/com/tamnara/backend/news/repository/NewsSearchRepositoryImpl.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsService.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
- backend/src/test/java/com/tamnara/backend/news/controller/NewsControllerTest.java
- backend/src/test/java/com/tamnara/backend/news/repository/NewsRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/service/NewsServiceImplTest.java
closes #212 
<br/>
<br/>
- **작업한 파일:** `news.repository.NewsRepository`, `news.repository.NewsSearchRepository`, `news.repository.NewsSearchRepositoryImpl`
- **작업한 내용:**
- QueryDSL 설정 추가하여 환경 구축하고 뉴스 검색 리포지토리 메서드 및 테스트에 적용
- 입력받은 태그 목록에 포함되는 태그와 연관된 모든 뉴스를 (일치율 ASC, 업데이트일자 DESC, 뉴스 ID DESC) 기준으로 정렬하고 페이징 처리하여 반환하는 리포지토리 메서드 추가
- **테스트 목록**
- 키워드 기반 뉴스 목록 검색 결과 조회 검증
- 검색어 목록과 태그 목록이 정확히 일치하는 뉴스가 최상위에 존재하는가.
- 검색어 목록과 교집합인 태그 목록을 가진 뉴스가 검색 결과에 포함되는가.
- 검색어 목록의 부분집합인 태그 목록을 가진 뉴스가 검색 결과에 포함되는가.
- 가중치가 높을수록 상위에 정렬되는가.
- 가중치가 동일할 경우, (updatedAt DESC, id DESC) 기준으로 정렬되는가.
- 가중치가 0인 뉴스가 검색 결과에 포함되지 않는가.
<br/>
- **작업한 파일:** `news.service.NewsServiceImpl`
- **작업한 내용:** 입력받은 태그 목록에서 중복을 제거하고 해당되는 뉴스들을 찾아, 응답 DTO 형식에 맞춰 반환하는 서비스 메서드 추가
- **테스트 목록**
- 뉴스 검색 결과 조회 검증
- 태그 수 미달 시 뉴스 검색 예외 처리 검증
- 태그 수 …
> feat: 뉴스 검색 기능 구현

- backend/src/main/java/com/tamnara/backend/poll/controller/PollController.java
- backend/src/main/java/com/tamnara/backend/poll/domain/VoteStatistics.java
- backend/src/main/java/com/tamnara/backend/poll/dto/OptionResult.java
- backend/src/main/java/com/tamnara/backend/poll/dto/PollStatisticsResponse.java
- backend/src/main/java/com/tamnara/backend/poll/service/VoteStatisticsService.java
#253 
- `VoteStatisticsService#getPollStatistics(Long pollId)` 메서드 추가
- 해당 투표의 모든 선택지를 대상으로 통계 조회
- 통계가 존재하지 않으면 `VoteStatistics.zero()`로 기본값 제공
- `PollController`에 `/polls/{pollId}/stats` 엔드포인트 추가
- 로그인 및 `State.ACTIVE` 사용자에 한해 접근 허용
- 통계 응답용 DTO 정의:
- `PollStatisticsResponse`: 투표 ID, 전체 투표 수, 선택지별 결과 목록 포함
- `OptionResult`: 옵션 ID, 제목, 투표 수 포함
---
- `VoteStatistics` 도메인에 `zero()` 정적 메서드 추가 (기본 통계 객체 생성용)
---
```json
{
"success": true,
"message":  "요청하신 정보를 성공적으로 불러왔습니다.",
"data": {
"pollId": 1,
"results": [
{ "optionId": 101, "title": "옵션 A", "count": 10 },
{ "optionId": 102, "title": "옵션 B", "count": 5 }
],
"totalVotes": 15
}
}
```
---
- 프론트엔드에서 투표 결과 시각화 가능
- 통계가 누락된 경우에도 안정적으로 0을 반환하여 UI 오류 방지
---
- 유저가 투표 결과를 언제 볼 수 있는지 조건 제어 (예: 투표 종료 후 공개 등)
- 통계 캐싱 or TTL 설정 고려
---
200 OK (투표 결과 …
> feat: 투표 통계 조회 API 구현

- backend/src/main/java/com/tamnara/backend/news/repository/NewsRepository.java
- backend/src/main/java/com/tamnara/backend/news/service/AIServiceImpl.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
- backend/src/test/java/com/tamnara/backend/news/repository/NewsRepositoryTest.java
closes #262
<br/>
<br/>
- **작업한 파일:** `news.repository.NewsRepository`
- **작업한 내용:** 조회수 증가 리포지토리 메서드 추가
- **테스트 목록**: 뉴스 조회수 증가 시 수정일자 변경되지 않고 유지 검증
<br/>
- **작업한 파일:** `news.service.NewsServiceImpl`
- **작업한 내용:** `getNewsDetail()`의 기존 조회수 증가 로직을 리포지토리 호출로 대체
<br/>
- 응답의 `updatedAt`이 과거로 나타나는 것을 확인
- DB의 `updated_at`이 변경되지 않고, `view_count`가 1 올라가는 것을 확인
> fix: 뉴스 상세 조회 시 뉴스의 수정일자가 현재 시점으로 변경되는 버그 해결

- backend/src/test/java/com/tamnara/backend/auth/service/KakaoServiceTest.java
- backend/src/test/java/com/tamnara/backend/global/util/CreateUserUtil.java
- backend/src/test/java/com/tamnara/backend/global/util/TestUtil.java
- `CreateUserUtils` → `CreateUserUtil`로 클래스명 변경 및 `global.util` 패키지로 이동
- `TestUtils` → `TestUtil`로 클래스명 변경 및 `global.util` 패키지로 이동
- 테스트 코드(`KakaoServiceTest`) 내 import 경로 및 클래스명 전반 수정
---
- 테스트 유틸 클래스들을 프로젝트 내 공통 유틸리티 위치(`global.util`)로 이동하여 구조 통일
- 클래스명 접미사 `Utils` → `Util`로 일관성 있는 네이밍 적용
---
- 테스트 유틸 관리 편의성 향상
- 실제 서비스 유틸리티와 테스트 유틸리티의 명확한 분리
---
- 테스트 코드 외 기능 로직에는 영향 없음
- 향후 다른 테스트 클래스에서도 공통 유틸을 재사용 가능
> chore: 테스트 유틸리티 클래스 위치 이동 및 네이밍 정리

- backend/src/main/java/com/tamnara/backend/poll/domain/VoteStatistics.java
- backend/src/main/java/com/tamnara/backend/poll/repository/PollOptionRepository.java
- backend/src/main/java/com/tamnara/backend/poll/repository/PollRepository.java
- backend/src/test/java/com/tamnara/backend/poll/domain/PollTest.java
- backend/src/test/java/com/tamnara/backend/poll/repository/PollOptionRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/poll/repository/PollRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/poll/repository/VoteRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/poll/repository/VoteStatisticsRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/poll/util/PollOptionTestBuilder.java
- backend/src/test/java/com/tamnara/backend/poll/util/PollTestBuilder.java
- backend/src/test/java/com/tamnara/backend/poll/util/VoteTestBuilder.java
- backend/src/test/java/com/tamnara/backend/user/repository/UserRepositoryTest.java
#198 
---
`Poll`, `PollOption`, `Vote`, `VoteStatistics` 엔티티에 대한 Repository 단위 테스트를 작성했습니다.  
각 Repository의 기본 CRUD 및 쿼리 메서드 동작을 검증합니다.
---
1. `PollRepositoryTest`
- Poll 저장 및 조회 테스트
- `findByState(PollState)` 동작 확인
- `findByEndAtAfter(LocalDateTime)` 동작 확인
2. `PollOptionRepositoryTest`
- PollOption 저장 및 조회 테스트
- `findByPollId(Long)`로 옵션 리스트 조회 확인
3. `VoteRepositoryTest`
- `findByUserIdAndPollId()` 로 유저의 투표 조회
- `findByPollId()`로 투표 목록 조회
- `countByPollIdAndOptionId()`로 특정 옵션에 대한 투표 수 조회
- `JPAQueryFactory` 의존성 문제로 `@MockBean` 처리
4. `VoteStatisticsRepositoryTest`
- `VoteStatistics.zero()` 저장 테스트
- `findByPollId()`, `findByPollIdAndOptionId()` 쿼리 테스트
- 복합 유니크 제약(`poll_id + option_id`) 중복 저장 시 예외 검증
- 테스트 환경에서 `@CreatedDate` 반영을 위해 `TestJpaAuditingConfig` 추가
---
- 테스트 편의성을 위한 Builder 클래스 추가 …
> test: Poll 도메인 관련 Repository 단위 테스트 추가

- backend/src/main/java/com/tamnara/backend/global/config/SchedulingConfig.java
- backend/src/main/java/com/tamnara/backend/news/constant/NewsServiceConstant.java
- backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
- backend/src/main/java/com/tamnara/backend/news/dto/request/AIHotissueRequest.java
- backend/src/main/java/com/tamnara/backend/news/dto/response/AIHotissueResponse.java
- backend/src/main/java/com/tamnara/backend/news/repository/NewsRepository.java
- backend/src/main/java/com/tamnara/backend/news/service/AIService.java
- backend/src/main/java/com/tamnara/backend/news/service/AIServiceImpl.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsSchedulerService.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsSchedulerServiceImpl.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsService.java
- backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
- backend/src/test/java/com/tamnara/backend/news/controller/NewsControllerTest.java
- backend/src/test/java/com/tamnara/backend/news/repository/NewsRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/service/NewsSchedulerServiceImplTest.java
- backend/src/test/java/com/tamnara/backend/news/service/NewsServiceImplTest.java
closes #237 
<br/>
<br/>
1. **생성할 핫이슈 뉴스 개수에 대하여 상수 선언**
```java
public static final Integer HOTISSUE_CREATE_CNT = 3;
```
2. **`NewsRepository`에 핫이슈 업데이트 메서드 추가**
```java
@Modifying
@Query("UPDATE News n SET n.isHotissue = :isHotissue WHERE n.id = :newsId")
void updateIsHotissue(@Param("newsId") Long newsId, @Param("isHotissue") boolean isHotissue);
```
3. **`AIService`에 핫이슈 키워드 생성 요청 메서드 추가**
```java
WrappedDTO<AIHotissueResponse> createAIHotissueKeywords();
```
4. **`NewsService`에 핫이슈 뉴스 생성** 
- 뉴스 생성 로직 수정: 핫이슈 생성 시 모든 user 필드 null 처리 및 북마크 처리 생략
- 뉴스 업데이트 로직 수정
- `isHotissue` 필드를 true로 업데이트
- 업데이트 기간이 지나지 않았다면 `isHotissue` 필드 외 업데이트 생략
```java
@Override
@Transactional
public void createHotissueNews() {
// 1. 핫이슈 키워드 목록 생성을 요청한다.
AIHotissueResponse aiHotissueResponse; …
```
> feat: 뉴스 기능에 핫이슈 생성 및 오래된 뉴스 삭제 스케줄링 메서드 추가

- backend/src/main/java/com/tamnara/backend/alarm/constant/AlarmResponseMessage.java
- backend/src/main/java/com/tamnara/backend/alarm/constant/AlarmServiceConstant.java
- backend/src/main/java/com/tamnara/backend/alarm/controller/AlarmController.java
- backend/src/main/java/com/tamnara/backend/alarm/domain/Alarm.java
- backend/src/main/java/com/tamnara/backend/alarm/domain/AlarmType.java
- backend/src/main/java/com/tamnara/backend/alarm/domain/UserAlarm.java
- backend/src/main/java/com/tamnara/backend/alarm/dto/AlarmCardDTO.java
- backend/src/main/java/com/tamnara/backend/alarm/dto/response/AlarmListResponse.java
- backend/src/main/java/com/tamnara/backend/alarm/repository/AlarmRepository.java
- backend/src/main/java/com/tamnara/backend/alarm/repository/UserAlarmRepository.java
- backend/src/main/java/com/tamnara/backend/alarm/service/AlarmSchedulerService.java
- backend/src/main/java/com/tamnara/backend/alarm/service/AlarmSchedulerServiceImpl.java
- backend/src/main/java/com/tamnara/backend/alarm/service/AlarmService.java
- backend/src/main/java/com/tamnara/backend/alarm/service/AlarmServiceImpl.java
- backend/src/main/java/com/tamnara/backend/global/security/CustomAuthenticationEntryPoint.java
- backend/src/test/java/com/tamnara/backend/alarm/config/AlarmServiceMockConfig.java
- backend/src/test/java/com/tamnara/backend/alarm/controller/AlarmControllerTest.java
- backend/src/test/java/com/tamnara/backend/alarm/domain/AlarmTest.java
- backend/src/test/java/com/tamnara/backend/alarm/domain/UserAlarmTest.java
- backend/src/test/java/com/tamnara/backend/alarm/repository/AlarmRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/alarm/repository/UserAlarmRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/alarm/service/AlarmSchedulerServiceImplTest.java
- backend/src/test/java/com/tamnara/backend/alarm/service/AlarmServiceImplTest.java
closes #238 
<br/>
<br/>
- **작업한 파일:** `alarm.domain.Alarm`, `alarm.domain.AlarmType`, `alarm.domain.UserAlarm`
- **작업한 내용:**
- `alarms` 테이블에 해당하는 `Alarm` 엔티티 추가
- Alarm 엔티티의 `targetType` 필드에 해당하는 enum `AlarmType` 추가
- `user_alarm` 테이블에 해당하는 `UserAlarm` 엔티티 추가
- **테스트 목록**
- Alarm 도메인 단위 테스트
- 알림 기본값 초기화 검증
- 알림 제목과 내용과 타겟종류와 타겟ID 설정 검증
- ID가 동일하면 동일한 알림 검증
- 알림 타겟 종류의 전체 정의값 검증
- 문자열로부터 enum 변환 검증
- 잘못된 문자열이 enum 변환에 실패 검증
- UserAlarm 도메인 단위 테스트
- 회원알림 기본값 초기화 검증
- 회원알림 회원과 알림 설정 검증
- 회원알림 확인 여부와 확인 시간 설정 검증
- ID가 동일하면 동일한 회원알림 검증
<br/>
- **작업한 파일:** `alarm.repository.AlarmRepository`, `alarm.repository.UserAlarmRepository`
- **작업한 내용:**
- `AlarmRepository` 리포지토리 추가
- 타겟 종류와 타겟 ID로 알림 목록을 ID 내림차순으로 정렬하여 조회
- 기준보다 오래된 알림들을 일괄 삭제
- `UserAlarmRepository` 리포지토리 추가
- 회원 ID로 회원알림 목록 ID 내림차순 조회 …
> feat: 알림 기능 API 구현

- backend/src/main/java/com/tamnara/backend/BackendApplication.java
- backend/src/main/java/com/tamnara/backend/global/config/AsyncConfig.java
- backend/src/main/java/com/tamnara/backend/global/security/CustomAuthenticationEntryPoint.java
#294 
<br/>
<br/>
- **작업한 파일:** `BackendApplication`, `global.config.AsyncConfig`
- `@EnableAsync` 어노테이션을 메인 클래스에서 제거
- 비동기 설정 클래스를 추가하여 `@EnableAsync` 어노테이션 적용
```java
@Configuration
@EnableAsync
public class AsyncConfig {
}
```
> refactor: 비동기 설정을 Config 클래스로 분리하여 책임 분리

- backend/src/main/java/com/tamnara/backend/poll/dto/PollCreateRequest.java
- backend/src/main/java/com/tamnara/backend/poll/dto/PollOptionCreateRequest.java
- backend/src/main/java/com/tamnara/backend/poll/service/PollService.java
- backend/src/test/java/com/tamnara/backend/poll/service/PollServiceTest.java
- backend/src/test/java/com/tamnara/backend/poll/service/VoteServiceTest.java
- backend/src/test/java/com/tamnara/backend/poll/service/VoteStatisticsServiceTest.java
- backend/src/test/java/com/tamnara/backend/poll/util/PollCreateRequestTestBuilder.java
- backend/src/test/java/com/tamnara/backend/poll/util/PollTestBuilder.java
#284 
- **PollServiceTest**
- `createPoll` 정상 플로우 및 예외 처리(`minChoices` > `maxChoices`, `startAt` > `endAt`)
- `getPollById` 정상 및 Poll 미존재 시 예외 처리
- `schedulePoll`, `publishPoll`, `deletePoll`에 대한 상태 변경 테스트
- 이미 `PUBLISHED` 투표 존재 시 예외 반환 테스트
- **VoteServiceTest**
- 정상 투표 시나리오
- 잘못된 투표 옵션/선택 수/중복 투표 등 다양한 예외 시나리오 테스트
- **VoteStatisticsServiceTest**
- `generateAllStatistics` 실행 시 통계 생성/업데이트 검증
- `getPollStatistics` 정상 응답 및 Poll 미존재 시 예외 발생 검증
각 테스트에서 Mockito를 활용한 repository/service mocking을 적용해 실제 비즈니스 로직이 정상 동작하는지 검증함.
> feat:  단위 테스트 추가 for PollService, VoteService, and VoteStatisticsService

- backend/src/test/java/com/tamnara/backend/poll/scheduler/PollStateSchedulerTest.java
- backend/src/test/java/com/tamnara/backend/poll/scheduler/VoteStatisticsSchedulerTest.java
#296 
`PollStateScheduler`와 `VoteStatisticsScheduler`에 대한 유닛 테스트를 추가하였습니다.
- `PollStateSchedulerTest` 작성
- 종료 시간이 지난 PUBLISHED 투표가 DELETED 상태로 전환되는지 검증
- 시작 시간이 현재보다 이전인 SCHEDULED 투표 중 가장 이른 투표가 PUBLISHED 상태로 전환되는지 검증
- `VoteStatisticsSchedulerTest` 작성
- 스케줄러가 `VoteStatisticsService.generateAllStatistics()`를 정확히 한 번 호출하는지 검증
- `@Scheduled` 어노테이션은 실제 테스트에서 실행되지 않기 때문에 해당 메서드를 직접 호출하여 로직을 검증하였습니다.
- 로그 출력은 검증하지 않고, 서비스 메서드 호출 여부에 중점을 두었습니다.
- 실제 스케줄링 동작 여부는 통합 테스트나 운영 환경에서 확인해야 합니다.
- 서비스 레이어에 대한 의존성을 Mocking하여 단위 테스트 수준에서 빠르게 검증할 수 있도록 구성했습니다.
> feat: Scheduler 관련 유닛 테스트 추가

- backend/src/main/java/com/tamnara/backend/BackendApplication.java
- backend/src/main/java/com/tamnara/backend/global/config/AsyncConfig.java
- backend/src/test/java/com/tamnara/backend/news/repository/CategoryRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/repository/NewsImageRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/repository/NewsTagRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/repository/TagRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/repository/TimelineCardRepositoryTest.java
#301 
<br/>
<br/>
- **작업한 파일:**
- 카테고리 리포지토리
- 뉴스 이미지 리포지토리
- 뉴스태그 리포지토리
- 태그 리포지토리
- 타임라인 카드 리포지토리
```java
@Import({JpaConfig.class, QuerydslConfig.class})
public class RepositoryTest
```
> fix: QueryDSL 의존성 포함 리포지토리 테스트에 QuerydslConfig 설정 추가

- backend/src/test/java/com/tamnara/backend/config/TestConfig.java
#301 
<br/>
<br/>
```java
@TestConfiguration
@Import({JpaConfig.class, QuerydslConfig.class})
public class TestConfig {
}
```
> feat: JpaConfig와 QuerydslConfig를 추가한 테스트용 설정 클래스 추가

- backend/src/test/java/com/tamnara/backend/alarm/repository/AlarmRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/alarm/repository/UserAlarmRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/bookmark/repository/BookmarkRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/comment/repository/CommentRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/repository/CategoryRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/repository/NewsImageRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/repository/NewsRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/repository/NewsTagRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/repository/TagRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/news/repository/TimelineCardRepositoryTest.java
#301 
<br/>
<br/>
```java
@DataJpaTest
@Import(TestConfig.class)
@ActiveProfiles("test")
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
public class XXXRepositoryTest
```
> refactor: 리포지토리 테스트의 @import 목록을 TestConfig로 변경

- backend/src/test/java/com/tamnara/backend/global/util/CreateUserUtil.java
- backend/src/test/java/com/tamnara/backend/poll/controller/PollControllerIntegrationTest.java
#299 
- `PollController`의 주요 API에 대한 통합 테스트 작성
- 투표 생성(createPoll)
- 투표 조회(getPollInfo)
- 투표 제출(vote)
- 투표 통계 조회(getPollStatistics)
- 투표 스케줄링(schedule)
- 인증이 필요한 요청에 대해 사용자 객체(`UserDetailsImpl`)와 csrf 설정을 통해 테스트 통과 처리
- `VoteService`, `PollService`, `VoteStatisticsService`를 MockBean으로 설정하여 의존성 분리
> feat: PollController 통합 테스트 구현

- backend/build.gradle
- backend/src/main/java/com/tamnara/backend/comment/dto/CommentDTO.java
- backend/src/main/java/com/tamnara/backend/comment/service/CommentServiceImpl.java
- backend/src/main/java/com/tamnara/backend/global/config/QuerydslConfig.java
- backend/src/test/java/com/tamnara/backend/comment/controller/CommentControllerTest.java
- backend/src/test/java/com/tamnara/backend/comment/repository/CommentRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/comment/service/CommentServiceImplTest.java
- backend/src/test/java/com/tamnara/backend/config/TestConfig.java
#312 
<br/>
<br/>
- **작업한 파일:** `comment.dto.CommentDTO`
- **작업한 내용:** `username` 필드 추가
```java
public class CommentDTO {
...
private String username;
...
}
```
```java
List<CommentDTO> commentDTOList = new ArrayList<>();
for (Comment c : comments.getContent()) {
CommentDTO dto = new CommentDTO(
...
c.getUser().getUsername(),
...
);
commentDTOList.add(dto);
}
```
> feat: 댓글 목록 조회 응답에 회원 이름 추가

- backend/src/main/java/com/tamnara/backend/comment/repository/CommentRepository.java
- backend/src/main/java/com/tamnara/backend/comment/service/CommentServiceImpl.java
- backend/src/test/java/com/tamnara/backend/comment/repository/CommentRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/comment/service/CommentServiceImplTest.java
#400 
<br/>
<br/>
- **작업한 파일:** `/comment/repository/CommentRepository`
- **작업 내용:** 비즈니스 로직에 맞게 리포지토리 메서드명 수정
```java
@Repository
public interface CommentRepository extends JpaRepository<Comment, Long> {
Page<Comment> findAllByNewsIdOrderByIdDesc(@Param("id") Long id, Pageable pageable);
}
```
> fix: 댓글 목록 조회 리포지토리 메서드명을 최신순 정렬 방식에 맞게 변경

- backend/src/main/java/com/tamnara/backend/auth/client/KakaoApiClientImpl.java
- backend/src/main/java/com/tamnara/backend/auth/constant/KakaoOAuthConstant.java
- backend/src/main/java/com/tamnara/backend/auth/service/KakaoServiceImpl.java
- backend/src/main/java/com/tamnara/backend/user/controller/UserController.java
- backend/src/main/java/com/tamnara/backend/user/domain/User.java
- backend/src/main/java/com/tamnara/backend/user/repository/UserRepository.java
- backend/src/main/java/com/tamnara/backend/user/service/UserService.java
- backend/src/main/java/com/tamnara/backend/user/service/UserServiceImpl.java
- backend/src/test/java/com/tamnara/backend/auth/controller/KakaoControllerIntegrationTest.java
- backend/src/test/java/com/tamnara/backend/user/controller/UserControllerIntegrationTest.java
- backend/src/test/java/com/tamnara/backend/user/repository/UserRepositoryTest.java
- backend/src/test/java/com/tamnara/backend/user/service/UserServiceTest.java
#405 #407 #409 
<br/>
<br/>
- **작업한 파일:** `user.repository.UserRepository`
- **작업 내용**
- `existsByUsername()`(닉네임 존재 여부 확인 메서드) 제거
- 이메일 중복 허용에 따라 `findByEmailAndProvider()`(이메일과 Provider로 회원 조회 메서드) 제거
- 서비스 로직에서 해당 리포지토리 메서드를 호출하는 코드 제거
<br/>
- **작업한 파일:** `user.service.UserService`, `user.service.UserServiceImpl`
- **작업 내용**
- `isUsernameAvailable()`(닉네임 사용 가능 여부 확인 서비스 메서드) 제거
- 회원가입, 회원정보 수정 서비스에서 닉네임 중복 여부 확인 로직 제거
<br/>
- **작업한 파일:** `user.controller.UserController`
- **작업 내용**
- `/users/check-nickname` 엔드포인트에 해당하는 API 제거
> feat: 카카오 OAuth 링크 상수화 및 Users 도메인의 일부 필드 중복 허용, 닉네임 중복 여부 확인 API 제거

- backend/src/main/java/com/tamnara/backend/auth/controller/AuthController.java
- backend/src/main/java/com/tamnara/backend/auth/service/AuthServiceImpl.java
- backend/src/main/java/com/tamnara/backend/auth/service/KakaoServiceImpl.java
#475 
<br/>
<br/>
- **작업한 파일:**
- `auth.controller.AuthController`
- `auth.service.AuthServiceImpl`
- `auth.service.KakaoServiceImpl`
- **작업 내용**
- 클래스에 `@Slf4j` 어노테이션 추가
- `log.info`/`log.warn`/`log.error` 로깅 추가
- 포맷: `[기능] 서비스 메서드 (시작/처리 중/완료) - 세부 로그`
> feat: 인증 기능의 서비스 로직에 로깅 추가

- backend/src/main/java/com/tamnara/backend/auth/client/KakaoApiClientImpl.java
- backend/src/main/java/com/tamnara/backend/auth/constant/AuthResponseMessage.java
- backend/src/main/java/com/tamnara/backend/auth/service/AuthServiceImpl.java
- backend/src/main/java/com/tamnara/backend/auth/service/KakaoServiceImpl.java
- backend/src/main/java/com/tamnara/backend/user/service/UserServiceImpl.java
#475 #476
<br/>
<br/>
- **작업한 파일:** `auth.client.KakaoClientImpl`
- **작업 내용** : 로깅 포맷 변경 및 추가
> feat: 카카오 클라이언트 서비스에 로깅 추가 및 로깅 포맷 일부 변경

- backend/src/main/java/com/tamnara/backend/poll/service/PollServiceImpl.java
- backend/src/test/java/com/tamnara/backend/poll/service/PollServiceImplTest.java
#494 
<br/>
<br/>
- **작업한 파일:** `poll/service/PollServiceImpl`
- **작업 내용:**
- `updatePollStates()`에서 투표 공개 처리 로직을 선행, 투표 삭제 처리 로직을 후행으로 로직 변경
- `updatePollStates()`에서 공개 예정 투표가 없으면 earty return 처리
> fix: 투표 공개 상태 업데이트 서비스에서 공개 예정 투표가 없으면 early return 처리
